# test.andon.yml
pipelines:
  Zuul:
    environment_variables:
      SONARUSER: admin
      SONARPASSWORD: admin
    group: eCommerce
    materials:
      zuul:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/tieto-devops-demos/microservice-demo-zuul-server.git
    stages:
      - build: # name of stage
          jobs:
            maven: # name of the job
              andon: # andon job configuration
                image: "andon.artifactorypro.shared.pub.tds.tieto.com/andon-gocd-agent-java8-maven3:v18.2.0" # elastic agent image
                sonarqube: true
#                stormrunner: true
#                ui_def_secure_variables:
#                  - PASSWORD
#                ui_def_variables:
#                  - USER
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c" 
                    - "mvn clean -Djava.security.egd=file:/dev/./urandom install"
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c" 
                    - "mvn sonar:sonar -Dsonar.login=$SONARUSER -Dsonar.password=$SONARPASSWORD -Dsonar.host.url=http://sonarqube:9000"
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c" 
                    - "docker build -f Dockerfile -t zuul:$GO_PIPELINE_COUNTER ."                    
